from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional, Sequence

from sqlalchemy import bindparam, text

from backend.scraper.db import get_engine as get_shared_engine


class Error(Exception):
    pass


class OperationalError(Error):
    pass


class IntegrityError(Error):
    pass


DatabaseError = Error
ProgrammingError = Error
InterfaceError = Error
NotSupportedError = Error
InternalError = Error
DataError = Error
Warning = Error


class Row(dict):
    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


@dataclass
class _PreparedQuery:
    sql: str
    params: dict[str, Any]
    expanding_keys: tuple[str, ...] = ()
    noop: bool = False
    insert_table: Optional[str] = None


def _coerce_sql(sql: Any) -> str:
    if hasattr(sql, "text"):
        return str(getattr(sql, "text"))
    return str(sql or "")


def _schema_column_query(table_name: str) -> _PreparedQuery:
    return _PreparedQuery(
        sql="""
        SELECT
            ordinal_position - 1 AS cid,
            column_name AS name,
            data_type AS type,
            CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
            column_default AS dflt_value,
            CASE WHEN position('nextval' in COALESCE(column_default, '')) > 0 THEN 1 ELSE 0 END AS pk
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = :table_name
        ORDER BY ordinal_position
        """,
        params={"table_name": table_name},
    )


def _rewrite_schema_sql(sql_text: str) -> str:
    rewritten = sql_text
    rewritten = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "bigint generated by default as identity primary key",
        rewritten,
        flags=re.IGNORECASE,
    )
    rewritten = re.sub(r"\bINTEGER\b", "bigint", rewritten, flags=re.IGNORECASE)
    rewritten = re.sub(r"\bREAL\b", "double precision", rewritten, flags=re.IGNORECASE)
    rewritten = re.sub(r"datetime\(([^)]+)\)", r"CAST(\1 AS timestamp)", rewritten, flags=re.IGNORECASE)
    return rewritten


def _prepare_query(sql: Any, params: Optional[Sequence[Any] | dict[str, Any]] = None) -> _PreparedQuery:
    raw_sql = _coerce_sql(sql).strip().rstrip(";")
    if not raw_sql:
        return _PreparedQuery(sql="SELECT 1 WHERE 1=0", params={}, noop=True)

    table_info_match = re.match(r"PRAGMA\s+table_info\(([^)]+)\)", raw_sql, flags=re.IGNORECASE)
    if table_info_match:
        return _schema_column_query(table_info_match.group(1).strip().strip("\"'"))

    if re.match(r"VACUUM$", raw_sql, flags=re.IGNORECASE):
        return _PreparedQuery(sql="SELECT 1", params={}, noop=True)

    if isinstance(params, dict):
        rewritten_sql = raw_sql
        bind_params = dict(params)
        expanding_keys: list[str] = []
    else:
        rewritten_sql = []
        bind_params = {}
        expanding_keys = []
        raw_params = list(params or [])
        param_index = 0
        for char_index, char in enumerate(raw_sql):
            if char != "?":
                rewritten_sql.append(char)
                continue
            key = f"p{param_index}"
            previous_chunk = raw_sql[max(0, char_index - 20):char_index].upper()
            rewritten_sql.append(f":{key}")
            value = raw_params[param_index]
            if previous_chunk.rstrip().endswith("IN (") and isinstance(value, (list, tuple, set)):
                bind_params[key] = list(value)
                expanding_keys.append(key)
            else:
                bind_params[key] = value
            param_index += 1
        rewritten_sql = "".join(rewritten_sql)

    insert_table = None
    ignore_match = re.match(r"INSERT\s+OR\s+IGNORE\s+INTO\s+([\w\".]+)(.*)$", rewritten_sql, flags=re.IGNORECASE | re.DOTALL)
    if ignore_match:
        insert_table = ignore_match.group(1).strip().strip('"')
        rewritten_sql = f"INSERT INTO {ignore_match.group(1)}{ignore_match.group(2)} ON CONFLICT DO NOTHING"

    replace_match = re.match(
        r"INSERT\s+OR\s+REPLACE\s+INTO\s+([\w\".]+)\s*\(([^)]+)\)\s*VALUES\s*\((.+)\)$",
        rewritten_sql,
        flags=re.IGNORECASE | re.DOTALL,
    )
    if replace_match:
        insert_table = replace_match.group(1).strip().strip('"')
        columns = [part.strip().strip('"') for part in replace_match.group(2).split(",")]
        conflict_column = columns[0]
        assignments = ", ".join(f"{column} = EXCLUDED.{column}" for column in columns[1:])
        rewritten_sql = (
            f"INSERT INTO {replace_match.group(1)} ({replace_match.group(2)}) VALUES ({replace_match.group(3)}) "
            f"ON CONFLICT ({conflict_column}) DO UPDATE SET {assignments}"
        )

    if re.match(r"(CREATE|ALTER)\s", rewritten_sql, flags=re.IGNORECASE):
        rewritten_sql = _rewrite_schema_sql(rewritten_sql)

    return _PreparedQuery(
        sql=rewritten_sql,
        params=bind_params,
        expanding_keys=tuple(expanding_keys),
        insert_table=insert_table,
    )


class Cursor:
    def __init__(self, connection: "Connection") -> None:
        self.connection = connection
        self._rows: list[Any] = []
        self.rowcount = -1
        self.lastrowid: Optional[int] = None

    def execute(self, sql: Any, params: Optional[Sequence[Any] | dict[str, Any]] = None) -> "Cursor":
        prepared = _prepare_query(sql, params)
        if prepared.noop:
            self._rows = []
            self.rowcount = 0
            return self

        statement = text(prepared.sql)
        for key in prepared.expanding_keys:
            statement = statement.bindparams(bindparam(key, expanding=True))
        try:
            result = self.connection._conn.execute(statement, prepared.params)
        except Exception as exc:
            raise OperationalError(str(exc)) from exc

        self.rowcount = int(result.rowcount or 0)
        if result.returns_rows:
            mapped_rows = [dict(row) for row in result.mappings().all()]
            self._rows = [Row(row) if self.connection.row_factory is Row else tuple(row.values()) for row in mapped_rows]
        else:
            self._rows = []

        if prepared.insert_table and self.rowcount > 0:
            try:
                row = self.connection._conn.execute(
                    text("SELECT currval(pg_get_serial_sequence(:table_name, 'id')) AS last_id"),
                    {"table_name": prepared.insert_table},
                ).mappings().first()
                if row and row.get("last_id") is not None:
                    self.lastrowid = int(row["last_id"])
            except Exception:
                self.lastrowid = None
        return self

    def executemany(self, sql: Any, seq_of_params: Iterable[Sequence[Any] | dict[str, Any]]) -> "Cursor":
        total = 0
        last_id = None
        for param_set in seq_of_params:
            self.execute(sql, param_set)
            total += max(self.rowcount, 0)
            last_id = self.lastrowid
        self.rowcount = total
        self.lastrowid = last_id
        return self

    def fetchone(self) -> Any:
        if not self._rows:
            return None
        return self._rows.pop(0)

    def fetchall(self) -> list[Any]:
        rows = list(self._rows)
        self._rows = []
        return rows


class Connection:
    def __init__(self, db_path: str | Path = "runtime-db") -> None:
        self.db_path = db_path
        self.row_factory: Optional[type[Row]] = None
        self._ctx = get_shared_engine(str(db_path)).begin()
        self._conn = None

    def __enter__(self) -> "Connection":
        self._conn = self._ctx.__enter__()
        return self

    def __exit__(self, exc_type, exc, tb) -> bool:
        return bool(self._ctx.__exit__(exc_type, exc, tb))

    def cursor(self) -> Cursor:
        return Cursor(self)

    def execute(self, sql: Any, params: Optional[Sequence[Any] | dict[str, Any]] = None) -> Cursor:
        return self.cursor().execute(sql, params)

    def executemany(self, sql: Any, seq_of_params: Iterable[Sequence[Any] | dict[str, Any]]) -> Cursor:
        return self.cursor().executemany(sql, seq_of_params)

    def commit(self) -> None:
        return None

    def rollback(self) -> None:
        return None

    def close(self) -> None:
        return None


def connect(db_path: str | Path = "runtime-db", *args: Any, **kwargs: Any) -> Connection:
    del args, kwargs
    return Connection(db_path=db_path)