-- Run this once in Supabase SQL Editor.
-- Adds task/runtime tables and worker-claim columns needed for primary-mode workers.

create table if not exists public.system_tasks (
    id bigint generated by default as identity primary key,
    user_id text not null default 'legacy',
    task_type text not null,
    status text not null,
    source text default 'api',
    worker_id text,
    created_at text not null,
    started_at text,
    finished_at text,
    updated_at text,
    request_payload text,
    result_payload text,
    error text
);

alter table if exists public.system_tasks
    add column if not exists user_id text not null default 'legacy';

alter table if exists public.system_tasks
    add column if not exists worker_id text;

alter table if exists public.system_tasks
    add column if not exists updated_at text;

create table if not exists public.system_runtime (
    key text primary key,
    value text,
    updated_at text not null
);

create index if not exists idx_system_tasks_type_id
    on public.system_tasks(task_type, id desc);

create index if not exists idx_system_tasks_status_created
    on public.system_tasks(status, created_at, id);

create index if not exists idx_system_tasks_user_type_id
    on public.system_tasks(user_id, task_type, id desc);
