-- Run this in Supabase SQL Editor for project dwxunoinmgdqftvnaziz
-- This schema mirrors the runtime tables used by backend/app.py sync.

create table if not exists public.leads (
    id bigint generated by default as identity primary key,
    business_name text not null,
    website_url text,
    phone_number text,
    rating double precision,
    review_count bigint,
    address text not null,
    search_keyword text,
    scraped_at text,
    email text,
    insecure_site bigint default 0,
    main_shortcoming text,
    ai_description text,
    enriched_at text,
    enrichment_data text,
    status text,
    enrichment_status text default 'pending',
    sent_at text,
    generated_email_body text,
    last_sender_email text,
    crm_comment text,
    status_updated_at text,
    contact_name text,
    ai_score double precision,
    client_tier text default 'standard',
    next_mail_at text,
    last_contacted_at text,
    follow_up_count bigint default 0,
    worker_id bigint,
    assigned_worker_at text,
    paid_at text,
    open_tracking_token text,
    open_count bigint default 0,
    first_opened_at text,
    last_opened_at text,
    campaign_sequence_id bigint,
    campaign_step bigint default 1,
    ab_variant text,
    last_subject_line text,
    reply_detected_at text,
    bounced_at text,
    bounce_reason text,
    phone_formatted text,
    phone_type text,
    user_id text not null default 'legacy',
    unique (business_name, address)
);

create table if not exists public.workers (
    id bigint generated by default as identity primary key,
    worker_name text not null,
    role text not null,
    monthly_cost double precision not null default 0,
    status text not null default 'Active',
    comms_link text,
    created_at text not null,
    updated_at text not null,
    user_id text not null default 'legacy'
);

create table if not exists public.revenue_log (
    id bigint generated by default as identity primary key,
    user_id text not null default 'legacy',
    amount double precision not null,
    service_type text not null,
    lead_name text,
    lead_id bigint,
    is_recurring bigint not null default 0,
    date text not null
);

create table if not exists public.delivery_tasks (
    id bigint generated by default as identity primary key,
    lead_id bigint not null,
    worker_id bigint,
    business_name text not null,
    task_type text not null,
    status text not null default 'todo',
    notes text,
    due_at text not null,
    done_at text,
    position bigint,
    created_at text not null,
    updated_at text not null,
    user_id text not null default 'legacy'
);

create table if not exists public.worker_audit_log (
    id bigint generated by default as identity primary key,
    worker_id bigint,
    lead_id bigint,
    action text not null,
    message text,
    actor text not null default 'system',
    created_at text not null
);

create table if not exists public.lead_blacklist (
    id bigint generated by default as identity primary key,
    kind text not null,
    value text not null,
    reason text,
    created_at text not null
);

create table if not exists public.CampaignSequences (
    id bigint generated by default as identity primary key,
    user_id text not null default 'legacy',
    name text not null,
    step1_subject text,
    step1_body text,
    step2_delay_days bigint default 3,
    step2_subject text,
    step2_body text,
    step3_delay_days bigint default 7,
    step3_subject text,
    step3_body text,
    ab_subject_a text,
    ab_subject_b text,
    active boolean default true,
    created_at text not null,
    updated_at text not null
);

create table if not exists public.SavedTemplates (
    id bigint generated by default as identity primary key,
    user_id text not null default 'legacy',
    name text not null,
    category text default 'general',
    prompt_text text,
    subject_template text,
    body_template text,
    created_at text not null,
    updated_at text not null
);

create table if not exists public.CampaignEvents (
    id bigint generated by default as identity primary key,
    lead_id bigint,
    user_id text not null default 'legacy',
    email text,
    event_type text not null,
    subject_variant text,
    subject_line text,
    metadata_json text,
    occurred_at text not null
);

create table if not exists public.system_tasks (
    id bigint generated by default as identity primary key,
    task_type text not null,
    status text not null,
    source text default 'api',
    created_at text not null,
    started_at text,
    finished_at text,
    request_payload text,
    result_payload text,
    error text,
    user_id text not null default 'legacy'
);

create table if not exists public.system_runtime (
    key text primary key,
    value text,
    updated_at text not null
);

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    email text not null unique,
    password_hash text not null,
    salt text not null,
    niche text not null default 'B2B Service Provider',
    account_type text not null default 'entrepreneur',
    display_name text not null default '',
    contact_name text not null default '',
    token text unique,
    reset_token text,
    reset_token_expires_at text,
    created_at text not null
);

create unique index if not exists idx_lead_blacklist_kind_value
    on public.lead_blacklist(kind, value);

create index if not exists idx_workers_status
    on public.workers(status);

create index if not exists idx_delivery_tasks_status_due
    on public.delivery_tasks(status, due_at);

create index if not exists idx_delivery_tasks_lead
    on public.delivery_tasks(lead_id);

create index if not exists idx_worker_audit_created
    on public.worker_audit_log(created_at desc);

create index if not exists idx_system_tasks_type_id
    on public.system_tasks(task_type, id desc);

create index if not exists idx_users_token
    on public.users(token);

create index if not exists idx_users_reset_token
    on public.users(reset_token);

create index if not exists idx_users_niche
    on public.users(niche);

create index if not exists idx_leads_user_id
    on public.leads(user_id);

create index if not exists idx_leads_open_tracking_token
    on public.leads(open_tracking_token);

create index if not exists idx_campaign_sequences_user_active
    on public.CampaignSequences(user_id, active);

create index if not exists idx_saved_templates_user_category
    on public.SavedTemplates(user_id, category);

create index if not exists idx_campaign_events_user_type
    on public.CampaignEvents(user_id, event_type);

create index if not exists idx_workers_user_id
    on public.workers(user_id);

create index if not exists idx_delivery_tasks_user_id
    on public.delivery_tasks(user_id);

create index if not exists idx_delivery_tasks_user_position
    on public.delivery_tasks(user_id, position);

create index if not exists idx_system_tasks_user_id
    on public.system_tasks(user_id);

create index if not exists idx_revenue_log_user_id
    on public.revenue_log(user_id);
