-- Run this once in Supabase SQL Editor (project dwxunoinmgdqftvnaziz)
-- Adds task/runtime tables needed for full primary-mode migration.

create table if not exists public.system_tasks (
    id bigint generated by default as identity primary key,
    task_type text not null,
    status text not null,
    source text default 'api',
    created_at text not null,
    started_at text,
    finished_at text,
    request_payload text,
    result_payload text,
    error text
);

create table if not exists public.system_runtime (
    key text primary key,
    value text,
    updated_at text not null
);

create index if not exists idx_system_tasks_type_id
    on public.system_tasks(task_type, id desc);
