-- Run in Supabase SQL Editor when you want a full cloud reset.
-- This keeps schema and clears only table data.

TRUNCATE TABLE IF EXISTS public.worker_audit_log RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS public.delivery_tasks RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS public.system_tasks RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS public.system_runtime RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS public.revenue_log RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS public.mailer_meta RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS public.workers RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS public.lead_blacklist RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS public.leads RESTART IDENTITY CASCADE;
